INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Apple Juice','Beverages','Apple Juice',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Beer, bottle, pilsener, import','Beverages','Beer, bottle, pilsener, import',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Beer, can','Beverages','Beer, can',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Coffee','Beverages','Coffee',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Milk','Beverages','Milk',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Milk, organic','Beverages','Milk, organic',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Orange Juice, not from concentrate','Beverages','Orange Juice, not from concentrate',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Soda, bottle','Beverages','Soda, bottle',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Soda, bottle (Coke product)','Beverages','Soda, bottle (Coke product)',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Soda, can','Beverages','Soda, can',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Soda, can (Coke product)','Beverages','Soda, can (Coke product)',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Tea, green, bags','Beverages','Tea, green, bags',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Water, regular/drinking','Beverages','Water, regular/drinking',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Water, Sparkling/Mineral','Beverages','Water, Sparkling/Mineral',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Wine, table, Cabernet','Beverages','Wine, table, Cabernet',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Wine, table, Chardonnay','Beverages','Wine, table, Chardonnay',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Wine, table, White Zinfandel','Beverages','Wine, table, White Zinfandel',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Apple Sauce','Canned & Packaged Foods','Apple Sauce',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Barbeque Sauce','Canned & Packaged Foods','Barbeque Sauce',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Bread Crumbs','Canned & Packaged Foods','Bread Crumbs',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Cheery Pie Filling','Canned & Packaged Foods','Cheery Pie Filling',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Chicken Noodle Soup, condensed','Canned & Packaged Foods','Chicken Noodle Soup, condensed',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Chicken Noodle Soup, regular','Canned & Packaged Foods','Chicken Noodle Soup, regular',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Chips, potato chips','Canned & Packaged Foods','Chips, potato chips',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Coconut Milk','Canned & Packaged Foods','Coconut Milk',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Flour, all purpose','Canned & Packaged Foods','Flour, all purpose',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Flour, self rising','Canned & Packaged Foods','Flour, self rising',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Green Beans, canned','Canned & Packaged Foods','Green Beans, canned',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Honey','Canned & Packaged Foods','Honey',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Jalopeño Peppers, canned','Canned & Packaged Foods','Jalopeño Peppers, canned',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Ketchup','Canned & Packaged Foods','Ketchup',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Mandarin Oranges, canned','Canned & Packaged Foods','Mandarin Oranges, canned',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Mayonnaise','Canned & Packaged Foods','Mayonnaise',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Milk Chocolate Bar','Canned & Packaged Foods','Milk Chocolate Bar',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Mushrooms, stems/pieces','Canned & Packaged Foods','Mushrooms, stems/pieces',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Mustard, dijon','Canned & Packaged Foods','Mustard, dijon',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Mustard, yellow','Canned & Packaged Foods','Mustard, yellow',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Nutella','Canned & Packaged Foods','Nutella',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Oil, Canola, 100% pure','Canned & Packaged Foods','Oil, Canola, 100% pure',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Oil, Olive, 100% pure','Canned & Packaged Foods','Oil, Olive, 100% pure',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Oil, Olive, extra virgin','Canned & Packaged Foods','Oil, Olive, extra virgin',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Pasta, Egg Noodles','Canned & Packaged Foods','Pasta, Egg Noodles',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Pasta, Ellbow Maccaroni','Canned & Packaged Foods','Pasta, Ellbow Maccaroni',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Pasta, Penne Rigate','Canned & Packaged Foods','Pasta, Penne Rigate',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Pasta, Rotini/Rotelle/Fusilli','Canned & Packaged Foods','Pasta, Rotini/Rotelle/Fusilli',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Pasta, Spaghetti','Canned & Packaged Foods','Pasta, Spaghetti',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Peanut Butter','Canned & Packaged Foods','Peanut Butter',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Peanuts, roasted','Canned & Packaged Foods','Peanuts, roasted',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Pepper, black, ground','Canned & Packaged Foods','Pepper, black, ground',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Preserves','Canned & Packaged Foods','Preserves',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Pretzels','Canned & Packaged Foods','Pretzels',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Rice, instant, white','Canned & Packaged Foods','Rice, instant, white',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Rice, regular','Canned & Packaged Foods','Rice, regular',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Salad Dressing','Canned & Packaged Foods','Salad Dressing',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Salsa, medium hot','Canned & Packaged Foods','Salsa, medium hot',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Salt','Canned & Packaged Foods','Salt',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Soup, organic','Canned & Packaged Foods','Soup, organic',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Spaghetti Sauce','Canned & Packaged Foods','Spaghetti Sauce',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Sugar, brown','Canned & Packaged Foods','Sugar, brown',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Sugar, powdered','Canned & Packaged Foods','Sugar, powdered',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Sugar, white','Canned & Packaged Foods','Sugar, white',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Syrup, breakfast','Canned & Packaged Foods','Syrup, breakfast',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Tomato Paste','Canned & Packaged Foods','Tomato Paste',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Tomato Sauce','Canned & Packaged Foods','Tomato Sauce',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Tomato Soup, condensed','Canned & Packaged Foods','Tomato Soup, condensed',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Tomato Soup, regular','Canned & Packaged Foods','Tomato Soup, regular',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Tuna, chunky, in water','Canned & Packaged Foods','Tuna, chunky, in water',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Tuna, solid, in water','Canned & Packaged Foods','Tuna, solid, in water',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Vanilla Extract, pure','Canned & Packaged Foods','Vanilla Extract, pure',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Bagles, plain','Bakery, Breakfast, Cereal','Bagles, plain',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Baguette/French Bread','Bakery, Breakfast, Cereal','Baguette/French Bread',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Bread, 12 grain','Bakery, Breakfast, Cereal','Bread, 12 grain',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Cereal, Müsli style','Bakery, Breakfast, Cereal','Cereal, Müsli style',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Cocoa Rice Cereal','Bakery, Breakfast, Cereal','Cocoa Rice Cereal',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Corn Flakes, regular','Bakery, Breakfast, Cereal','Corn Flakes, regular',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Corn Flakes, sugar frosted','Bakery, Breakfast, Cereal','Corn Flakes, sugar frosted',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Croissants','Bakery, Breakfast, Cereal','Croissants',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Granola Bars, high fiber','Bakery, Breakfast, Cereal','Granola Bars, high fiber',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Granola Bars, regular','Bakery, Breakfast, Cereal','Granola Bars, regular',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Honey Crunch Oats','Bakery, Breakfast, Cereal','Honey Crunch Oats',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Hot Dog Buns','Bakery, Breakfast, Cereal','Hot Dog Buns',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Oat Meal','Bakery, Breakfast, Cereal','Oat Meal',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('White Bread/Toast, enriched','Bakery, Breakfast, Cereal','White Bread/Toast, enriched',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Breakfast Sausage, frozen','Frozen Foods','Breakfast Sausage, frozen',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Chicken Breasts, frozen','Frozen Foods','Chicken Breasts, frozen',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Chicken Nuggets, frozen','Frozen Foods','Chicken Nuggets, frozen',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Chicken Tenderloins, frozen','Frozen Foods','Chicken Tenderloins, frozen',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Fish, Flounder, frozen','Frozen Foods','Fish, Flounder, frozen',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Fish, Mahi Mahi, frozen','Frozen Foods','Fish, Mahi Mahi, frozen',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Fish, Tilapia, frozen','Frozen Foods','Fish, Tilapia, frozen',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('French Fries, frozen','Frozen Foods','French Fries, frozen',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Fruit, frozen','Frozen Foods','Fruit, frozen',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Ground Beef, frozen','Frozen Foods','Ground Beef, frozen',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Ground Turkey, frozen','Frozen Foods','Ground Turkey, frozen',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Ice Cream, premium','Frozen Foods','Ice Cream, premium',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Ice Cream, simple','Frozen Foods','Ice Cream, simple',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Pizza, frozen (premium)','Frozen Foods','Pizza, frozen (premium)',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Pizza, frozen (simple)','Frozen Foods','Pizza, frozen (simple)',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Veggies, frozen','Frozen Foods','Veggies, frozen',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Waffles, frozen','Frozen Foods','Waffles, frozen',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Aluminum Foil','Miscellaneous Kitchen Items','Aluminum Foil',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Paper Towles','Miscellaneous Kitchen Items','Paper Towles',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Plastic Wrap','Miscellaneous Kitchen Items','Plastic Wrap',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Apples, Gala, bag','Produce','Apples, Gala, bag',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Apples, Red/Golden Delicious, bag','Produce','Apples, Red/Golden Delicious, bag',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Carrots, whole','Produce','Carrots, whole',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Grapes, red','Produce','Grapes, red',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Lemons','Produce','Lemons',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Lettuce, iceberg','Produce','Lettuce, iceberg',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Mushrooms, whole','Produce','Mushrooms, whole',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Onions, yellow','Produce','Onions, yellow',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Oranges','Produce','Oranges',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Pears','Produce','Pears',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Potatoes, gold (Yukon)','Produce','Potatoes, gold (Yukon)',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Potatoes, red','Produce','Potatoes, red',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Potatoes, Russet','Produce','Potatoes, Russet',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Tomatoes','Produce','Tomatoes',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Bacon','Refrigerated Foods','Bacon',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Beef Stew Meat','Refrigerated Foods','Beef Stew Meat',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Brats, 4-6 pack','Refrigerated Foods','Brats, 4-6 pack',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Butter, real, unsalted/salted','Refrigerated Foods','Butter, real, unsalted/salted',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Cheese Singles (imitation)','Refrigerated Foods','Cheese Singles (imitation)',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Cheese, block (regular)','Refrigerated Foods','Cheese, block (regular)',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Cheese, Boursin','Refrigerated Foods','Cheese, Boursin',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Cheese, Brie','Refrigerated Foods','Cheese, Brie',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Cheese, shredded, Mexican style','Refrigerated Foods','Cheese, shredded, Mexican style',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Cheese, shredded, Mozarella','Refrigerated Foods','Cheese, shredded, Mozarella',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Cheese, sliced, deli','Refrigerated Foods','Cheese, sliced, deli',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Cheese, sliced, regular','Refrigerated Foods','Cheese, sliced, regular',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Cheese, wedge (real, deli)','Refrigerated Foods','Cheese, wedge (real, deli)',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Chocolate Chip Cookie Dough','Refrigerated Foods','Chocolate Chip Cookie Dough',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Cold Cuts, ham or chicken','Refrigerated Foods','Cold Cuts, ham or chicken',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Cold Cuts, turkey variety','Refrigerated Foods','Cold Cuts, turkey variety',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Cottage Cheese','Refrigerated Foods','Cottage Cheese',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Cream Cheese','Refrigerated Foods','Cream Cheese',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Cream, heavy whipping','Refrigerated Foods','Cream, heavy whipping',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Eggs, cage free','Refrigerated Foods','Eggs, cage free',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Eggs, regular','Refrigerated Foods','Eggs, regular',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Ground Beef (chuck), fresh','Refrigerated Foods','Ground Beef (chuck), fresh',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Ground Beef (sirloin), fresh','Refrigerated Foods','Ground Beef (sirloin), fresh',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Ground Turkey, fresh','Refrigerated Foods','Ground Turkey, fresh',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Ham, half','Refrigerated Foods','Ham, half',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Kielbasa','Refrigerated Foods','Kielbasa',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Margarine/Spread','Refrigerated Foods','Margarine/Spread',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Pancetta, diced','Refrigerated Foods','Pancetta, diced',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Pizza Dough','Refrigerated Foods','Pizza Dough',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Pork Tenderloin, small','Refrigerated Foods','Pork Tenderloin, small',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Ribs, Baby Back (pork, unseasoned)','Refrigerated Foods','Ribs, Baby Back (pork, unseasoned)',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Ribs, Spare Back (pork, unseasoned)','Refrigerated Foods','Ribs, Spare Back (pork, unseasoned)',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Salami, sliced','Refrigerated Foods','Salami, sliced',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Salami, whole','Refrigerated Foods','Salami, whole',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Sour Cream','Refrigerated Foods','Sour Cream',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Yoghurt, Dannon (etc.)','Refrigerated Foods','Yoghurt, Dannon (etc.)',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Yogurt, Fage, 2%, plain','Refrigerated Foods','Yogurt, Fage, 2%, plain',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Yogurt, Fage, w/ flavor','Refrigerated Foods','Yogurt, Fage, w/ flavor',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Yogurt, flavored, cup','Refrigerated Foods','Yogurt, flavored, cup',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Yogurt, greek style, plain','Refrigerated Foods','Yogurt, greek style, plain',0.99,10);
INSERT INTO cstore.product(product_name,ptype,description,price,quantity_available) values ('Yogurt, plain','Refrigerated Foods','Yogurt, plain',0.99,10);